services:
  postgres:
    image: postgres:latest
    container_name: database_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Brenno1234567
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: database_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Brenno1234567
      MONGO_INITDB_DATABASE: mongo_db
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: